FROM jenkins/jenkins:latest

USER root

#Install docker client binaries
RUN apt-get update && apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common \
    && curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose 
    # && curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey \
    # && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable" \
    # && apt-get update \
    # && apt-get -y install docker-ce