version: "3.7"

services: 
  web:
    container_name: flask_app
    build: 
      context: ./Application/
      dockerfile: Dockerfile
    networks:
      my-network:
        aliases:
          - flask-app
  server:
    image: nginx:latest
    container_name: nginx_server
    depends_on:
      - web
    volumes:
      - ./ngix/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8085:80
    networks:
      - my-network
      
networks:
  my-network: